/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

const Book = (props) => { 
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('models/scene.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group>
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="dad255dd2cf24ae0bb357684e49722b4fbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Scene" position={[-4.8, 0, 0.3]} rotation={[-Math.PI / 2, 0, 0]}>
                  <group name="Object_5" position={[-14, 15.8, 4.3]}>
                    <mesh
                      name="Scene_Texture-base_0"
                      castShadow
                      receiveShadow
                      geometry={nodes['Scene_Texture-base_0'].geometry}
                      material={materials['Texture-base']}
                    />
                    <mesh
                      name="Scene_Texture-base_0_node"
                      castShadow
                      receiveShadow
                      geometry={nodes['Scene_Texture-base_0_node'].geometry}
                      material={materials['Texture-base']}
                    />
                    <mesh
                      name="Scene_Texture-base-gloss-jpg_0"
                      castShadow
                      receiveShadow
                      geometry={nodes['Scene_Texture-base-gloss-jpg_0'].geometry}
                      material={materials['Texture-base-gloss-jpg']}
                    />
                    <mesh
                      name="Scene_Book-tittle_0"
                      castShadow
                      receiveShadow
                      geometry={nodes['Scene_Book-tittle_0'].geometry}
                      material={materials['Book-tittle']}
                    />
                  </group>
                  <group
                    name="Mill-wind-wheel"
                    position={[-35.8, -27.2, 3.9]}
                    rotation={[0.4, -0.4, -0.5]}>
                    <group
                      name="Object_11"
                      position={[-8.3, 39.9, -25.8]}
                      rotation={[-0.6, 0.1, 0.6]}>
                      <mesh
                        name="Mill-wind-wheel_Texture-base_0"
                        castShadow
                        receiveShadow
                        geometry={nodes['Mill-wind-wheel_Texture-base_0'].geometry}
                        material={materials['Texture-base']}
                      />
                    </group>
                  </group>
                  <group
                    name="Mill-water-wheel"
                    position={[3.7, -15.4, -0.4]}
                    rotation={[-1.9, 0, 0]}>
                    <group name="Object_14" position={[-17.7, 31.2, 4.8]}>
                      <mesh
                        name="Mill-water-wheel_Texture-base_0"
                        castShadow
                        receiveShadow
                        geometry={nodes['Mill-water-wheel_Texture-base_0'].geometry}
                        material={materials['Texture-base']}
                      />
                    </group>
                  </group>
                </group>
                <group
                  name="flag"
                  position={[-11.5, 12.5, -6.8]}
                  rotation={[-Math.PI / 2, 0, -Math.PI / 6]}>
                  <group name="Object_17" position={[-7.3, 9, -8.2]}>
                    <mesh
                      name="0"
                      castShadow
                      receiveShadow
                      geometry={nodes['0'].geometry}
                      material={materials['Texture-base']}
                      morphTargetDictionary={nodes['0'].morphTargetDictionary}
                      morphTargetInfluences={nodes['0'].morphTargetInfluences}
                    />
                  </group>
                </group>
                <group
                  name="flag-second"
                  position={[-11.5, 12.6, -26.2]}
                  rotation={[-Math.PI / 2, 0, 0]}>
                  <group name="Object_20" position={[-7.3, 9, -8.2]}>
                    <mesh
                      name="1"
                      castShadow
                      receiveShadow
                      geometry={nodes['1'].geometry}
                      material={materials['Texture-base']}
                      morphTargetDictionary={nodes['1'].morphTargetDictionary}
                      morphTargetInfluences={nodes['1'].morphTargetInfluences}
                    />
                  </group>
                </group>
                <group name="Waterfall" position={[-4.8, 0, 0.4]} rotation={[-Math.PI / 2, 0, 0]}>
                  <group name="Object_23" position={[-14, 15.8, 4.3]}>
                    <mesh
                      name="Waterfall_Texture-base-gloss-jpg_0"
                      castShadow
                      receiveShadow
                      geometry={nodes['Waterfall_Texture-base-gloss-jpg_0'].geometry}
                      material={materials['Texture-base-gloss-jpg']}
                    />
                  </group>
                </group>
                <group name="deers" position={[-23.1, 0, 14.9]} rotation={[-Math.PI / 2, 0, 0]}>
                  <group name="Object_26" position={[4.3, 30.4, 4.4]}>
                    <mesh
                      name="deers_Texture-base_0"
                      castShadow
                      receiveShadow
                      geometry={nodes['deers_Texture-base_0'].geometry}
                      material={materials['Texture-base']}
                    />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('models/scene.glb')

export default Book;
